urbanadventurer/WhatWeb

lib/target.rb
plugins/Django.rb
plugins/nginx.rb
plugins/open-graph-protocol.rb
plugins/passenger.rb

Fixed @body encoding to allow plugins to regexp against UTF-8 <body> content.
Updated Django.rb to check for django-ish cookies.

fixed @body encoding, added update to Django.rb

---

plugins/SillySmart.rb

Very simple detection of SillySmart php framework, it seems to often define a "slsBuild" JavaScript variable.

Add SillySmart plugin

---

lib/extend-http.rb

Avoid timeout deprecation warnings

---

plugins/bugtracker-net.rb
plugins/cloudflare.rb

Updated CloudFlare plugin & added a new one for BugTracker.NET

Added regex to detect CloudFlare email address protection feature & added new BugTracker.NET plugin

---

lib/plugins.rb

The first patch was a quick pass to change tabs to two spaces and start cleaning up indentation.
The second patch continues on indentation and also has formatting changes.

Quick clean up of lib/plugins.rb

---

README
lib/output.rb
whatweb

Log into elastic search added.
Authentication (Shield plugin for the Elastic stack) not supported.
```
--log-elastic-index     Name of the index to store results. Default: whatweb 
--log-elastic-host      Host:port of the elastic http interface. Default: 127.0.0.1:9200
```

Elastic ouput

---

lib/output.rb

Reduce length of targets.target column in SQL output #180

---

plugins/genexus.rb

Plugin for GeneXus, a tool for agile development.

Plugin - GeneXus

---

my-plugins/BigCommerce.rb
my-plugins/DemandWare.rb
my-plugins/OCP.rb

BigCommerce
DemandWare eCommerce System
Open Commerce Platform

New ecommerce plugins from csalazar

---

plugins/wordpress.rb

Added "wp-includes" and "wp-json" in href and src detection.

---

lib/target.rb

Clean incorrent UTF-8 byte sequences when loading from file

---

test/unit/test_scan.rb

Possible fix for #238 
Builds (except for Ruby 1.9 see PR #239) are passing 
https://travis-ci.org/andrericardo/WhatWeb/builds/339845097

Fix issue in test_scan where country is not the first result in array

---

plugins/odoo.rb

Hi,
this adds a plugin to detect [Odoo](https://www.odoo.com/).

adds Odoo plugin

---

plugins/bootstrap.rb

This plugin detects Bootstrap based on the JavaScript and Stylesheet includes.
Verified to be working against: http://hacking-challenge.herokuapp.com

Add plugin for bootstrap

---

plugins/bootstrap.rb

I improved the bootstrap plugin by adding aggressive detection based on bootstrap css and js files that leak version information

Improve bootstrap plugin

---

plugins-disabled/charset.rb

Added name to authors section and bumped version

---

.simplecov
Gemfile
Rakefile
test/enable_coverage.rb

tests: add SimpleCov for test coverage

---

plugins/phpmyadmin.rb

Add checksums for 3.5.8.2, 4.1.9, 4.6.6, 4.9.7 and 5.0.4 versions

Add checksums for new versions

---

.gitignore
plugins/joomla.rb

Add  '/administrator/manifests/files/joomla.xml' as a path that should be checked (if it exists, extract the matched version)

Add new file for detecting exact version in Joomla (aggressive mode)

---

plugins/apache-flink.rb

Add Apache Flink plugin

---

plugins/vmware-horizon.rb

Wanted to wait for feedback on my other PR first (since again, I'm pretty new to this), but this plugin development experience has been pretty smooth and easy so far, so I decided to try my hand at making my own plugin also. I'd love to know what you guys think about it!

Add VMware Horizon plugin

---

plugins/microsoft-iis.rb

Should be pretty self-explanatory. I'm pretty new to WhatWeb and its plugin development practices so please let me know if I can do anything to make reviewing PRs easier for you guys in the future!

Add IIS 8.5 "Under Construction" detection

---

plugins/dell-openmanage-switch-administrator.rb

Just going through my scans and adding everything that isn't getting picked up already. :)

Add Dell OpenManage Switch Administrator plugin

---

plugins/telerik.rb

Tested against Alexa Top 100 and confirmed using these two public sites.  It was hard to find public sites to check against.
https://www.healthstream.com
https://www.madisonareaymca.org
The Telerik UI seems to have something in common with the Kendo UI (wappalyzer detects this) but the checks in this pull request I believe focus at least on the Telerik UI for ASP.NET AJAX - https://www.telerik.com/products/aspnet-ajax.aspx 
Happy to rename or clarify if needed, not sure how much I can dig into the entire Telerik/Kendo thing to build out a full plugin, but this would be a basic start at one component.

New plugin for Telerik UI Framework

---

lib/whatweb.rb

fix error described in following issue: https://github.com/urbanadventurer/WhatWeb/issues/410

Update whatweb.rb - fix uninitialized constant error

---

plugins/cisco-adaptive-security-appliance.rb
plugins/goanywhere-web-client.rb

I noticed that some CISCO ASA instances are not discovered using the plugin. 
Hence, I introduced a new regex matching the location.replace that all those instances present.

CISCO ASA 
