urbanadventurer/WhatWeb

lib/target.rb
Allow this set of ciphers.
OpenSSL::SSL::SSLContext::DEFAULT_PARAMS[:ciphers] = "TLSv1:TLSv1.1:TLSv1.2:SSLv3:SSLv2"
=> fix issue with website only using TLSv1

Gemfile, Rakefile, test/unit.rb
Add simple unit tests.
``` bash
$ rake
Run options: --seed 10623
....Invalid custom plugin syntax: :text=>vmdbuhaz
./pentest/web/whatweb/lib/target.rb:189: warning: constant Target::TimeoutError is deprecated
.....
Finished in 9.598764s, 1.0418 runs/s, 2.2920 assertions/s.
10 runs, 22 assertions, 0 failures, 0 errors, 0 skips
```
``` bash
$ rake -T
rake all                   # Run all tests
rake bundle_audit          # Run bundle-audit
rake bundle_audit:check    # Check gems for vulns using bundle-audit
rake bundle_audit:update   # Update bundle-audit database
rake rdoc                  # Generate API documentation to doc/rdocs/index.html
rake rdoc:clobber_rdoc     # Remove RDoc HTML files
rake rdoc:rdoc             # Build RDoc HTML files
rake rdoc:rerdoc           # Rebuild RDoc HTML …
```
=> Add unit tests

lib/target.rb
should be so however whatweb doesn't output either ways (without this displays a warning)
http extended ruby 2.0 uses this const
=> ::TimeoutError is deprecated

whatweb
* fixed --max-redirects being off by one, if 1 it would follow 0 directs
* fixed possible issue in error where semaphore would be released when attempting a reentrant lock
I left in the use of semaphore in lib/output.rb as the indentation was inconsistent; I wouldn't mind changing it after #201.
=> Reuse workers + log through a single thread + fix --max-directs

whatweb
This PR raplaces nmap with `IPAddr` standard library for IP address range parsing.
We lose some niceties (`*` in particular) in favor of dropping the requirement for `nmap` to exist on the system and no longer having to fork, twice, to detect `nmap` then run `nmap`.
Common formats are supported:
* 192.168.0.0/24
* 192.168.0.1-192.168.0.254
* 192.168.0.1-10
=> Use IPAddr for IP range parsing

.travis.yml
It seems that Ruby 1.9 builds are not supported anymore, so it would help me to remove them from travis :)
=> Remove Ruby 1.9 - Ruby 1.x is EOL and no longer supported from Travis

plugins/jquery.rb
When The JQuery Version is stored in the filepath and not in the filename, the version is currently not detected. This PR adds the corresponding regex. This will e.g. match:
`<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.min.js"></script>`
=> feat: detect jquery when version appears in filepath

plugins/jquery.rb, plugins/typo3.rb
The TYPO3 Plugin does not match the version string from the MetaGenerator if the tag is not enclosed with a `\>`, but a `>` only.
This PR makes the regex forgiving, by discarding the closing tag.
=> Bugfix in TYPO3 Plugin Version Detection

whatweb
Scan method returns an array, but the string is required
=> Fixed bug in Basic Auth credentials parsing

plugins-disabled/charset.rb, whatweb
The logging to MongoDB was not working because it was still referring to the old naming of the output class.
In the charset plugin, the body was never referenced correctly, and for some reason the get_charset function was not able to be called inside the passive do-block, so I just pulled out the code and ran it directly since it was only called once anyway.
My knowledge of Ruby is very limited, but logging to MongoDB works now, as it did in version 0.4.9.
=> Fixed Mongodb logging and charset bugs

lib/target.rb
=> Fix some warnings of "URI.escape is obsolete"

Makefile
When build is being executed, the /usr/bin directory is not present by default.
Create it, if it is missing.
=> Create missing bin directory in DESTDIR

Makefile
The symbolic link should point to real directory and not to DESTDIR prefixed build directory.
=> Fix symbolic link

Makefile
With this change, one can run `make install PREFIX=/my/custom/prefix`.
=> Allow to install in a custom prefix

lib/extend-http.rb, lib/target.rb, whatweb
=> adds ability to specify bind address

plugins/adobe-experience-manager.rb
I realized that WhatWeb didn't have any plugin to detect Adobe Experience Manager (AEM) instances.  So, to get this started here's an initial plugin that borrows the regex searches from Wappalyzer as well as a Google dork for the login page.
=> Added initial plugin for Adobe Experience Manager CMS detection

lib/logging/mongodb.rb
This PR replaces insert_one() by replace_one() with upsert policy in mongo logging. With upsert, the document in mongo will be replaced if target already exists and inserted if the document doesn't exist. I think that it is more convenient than inserting when the only thing that you want to know is the latest version number of a middleware. I also realize that insert_one() would be better when you want to maintain a history of all the version updates (even repeating all the data about the target just changing the version number of a single attribute...)
Ideally, we should have an option to switch between insert or replace.
=> change mongo logging policy to upsert (update by default, insert if new)

lib/logging/mongodb.rb
According to the API docs for Mongo Client connection options:
https://api.mongodb.com/ruby/current/Mongo/Client.html#initialize-instance_method:~:text=characters-,.,%3A
the correct value for specifying the username of the connection string is **user**, not **username**.
Trying to log to mongo using "username" instead of "user" will yield the following error:
`ERROR Logging failed: https://domain.com - there are no users authenticated (13) (on localhost, legacy retry, attempt 1)`
It is also more clearly highlighted when using --debug option in whatweb:
`W, [2020-11-25T22:02:15.304776 #262609]  WARN -- : MONGODB | Unsupported client option 'username'. It will be ignored.`
The attached patch allows to connect using authentication options and insert logs into mongo without problems:
` …
=> Replace username by user in Mongo Client connection options

lib/logging/sql.rb
The previous version was quite broken:
https://github.com/urbanadventurer/WhatWeb/blob/3e7d5eeedcf678b5624955122097330f43563360/lib/logging/sql.rb#L46-L53
Specifically, [this line](https://github.com/urbanadventurer/WhatWeb/blob/3e7d5eeedcf678b5624955122097330f43563360/lib/logging/sql.rb#L51) is not doing what we suppose it'll do:
` "'" + s.tr("'", "\'") + "'"`
Apparently, it seems that a string like `escape'me` would be translated to `escape\'me` but that's not the case:
```
2.7.2 :055 > "escape'me".tr("'","\'")
=> "escape'me"
```
You can find a good explanation of why [here](https://stackoverflow.com/a/12701027/243532). 
So the `escape_for_sql` method wasn't really escaping anything o_O 
Finally, I think that this `if` branch is unneded: …
=> Fix escape_for_sql method

lib/helper.rb
The problem is in `lib/helper.rb`, `convert_to_utf8` method. It tries to change a frozen String. Probably because whatweb detects a multi-version CMS (e.g., Wordpress 4.x and 4.y.)
https://github.com/urbanadventurer/WhatWeb/blob/1b3516975571c3f59d686f82a6d2dbf6f1011029/lib/helper.rb#L38-L47
Tracing the origin of this bug I think that the main reason is the following:
https://github.com/urbanadventurer/WhatWeb/blob/1b3516975571c3f59d686f82a6d2dbf6f1011029/lib/plugins.rb#L58-L59
Plugins's names are frozen, so trying to encode them twice (or more) to UTF-8 (due to multiple-version detection) will yield the error.
With this PR I propose a simple workaround in `lib/helper.rb`.
I don't have a Ruby 2.0 version available here to test that branch of the if conditional. In fact, I'd suggest to …
=> Fix #311 - JSON Logging fails... UTF-8 can't modify frozen String
